#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:10:00
#PBS -l vmem=20gb

#bl2bids

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Guiomar Niso
# Contributor: Kami Salibayeva

# make output directory
mkdir -p out_dir

#python main.py
singularity exec docker://aunnikri642/app-freesurfer-mne-source-recon python3 main.py
