#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:10:00
#PBS -l vmem=20gb

#bl2bids

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Guiomar Niso

set -e
set -x

# Contributor: Kami Salibayeva

#python main.py
singularity exec docker://brainlifemeeg/mne:1.12.1 python3 main.py
